#!/usr/bin/env bash
# Generate the sample-output gallery: one markdown file per task under
# benchmarks/outputs/, containing every model's unedited answer to the same
# prompt (temperature 0, seed 42), for side-by-side quality comparison.
#
# Requires: curl, jq.
set -euo pipefail
export LC_ALL=C

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
BENCH_DIR=$(dirname "$SCRIPT_DIR")/benchmarks

OLLAMA_URL=${OLLAMA_URL:-http://localhost:11434}
BENCH_MODELS=${BENCH_MODELS:-"qwen3.5:4b mistral:7b llama3.1:8b ornith:9b qwen3.5:9b qwen3.5:9b-q8_0 gemma3:12b qwen3.6:35b"}
# Generous: thinking models (qwen3.5/3.6) spend most of it on hidden reasoning.
# num_ctx must be raised too — Ollama's 4,096 default silently truncates the
# generation once prompt + thinking + answer no longer fit.
GALLERY_NUM_PREDICT=${GALLERY_NUM_PREDICT:-6144}
GALLERY_NUM_CTX=${GALLERY_NUM_CTX:-8192}

TASKS="summarize extract code reasoning"

log() { printf '%s %s\n' "$(date +%H:%M:%S)" "$*" >&2; }
die() { log "ERROR: $*"; exit 1; }

for cmd in curl jq; do command -v "$cmd" >/dev/null || die "$cmd is required"; done
curl -sf "$OLLAMA_URL/api/version" >/dev/null || die "Ollama API not reachable at $OLLAMA_URL"

task_file() {
    case $1 in
    summarize) echo "$BENCH_DIR/prompts/long.txt" ;;
    *) echo "$BENCH_DIR/tasks/$1.txt" ;;
    esac
}

task_blurb() {
    case $1 in
    summarize) echo "Summarize a ~1,200-token infrastructure report in one paragraph (same prompt as the long-prompt performance scenario)." ;;
    extract) echo "Extract and deduplicate the ERROR lines of a service log into a JSON array — instruction following and structured output." ;;
    code) echo "Implement a duration-string parser in Python with validation, docstring and examples." ;;
    reasoning) echo "A GPU memory-budget word problem with a single verifiable answer (93 sessions)." ;;
    esac
}

# Prints the model's answer; strips <think> blocks some models emit.
generate() {
    local model=$1 prompt_file=$2 payload out
    # Model-default temperature (temp 0 sends thinking models into pathologically
    # verbose reasoning); fixed seed keeps a given run reproducible.
    payload=$(jq -n --arg model "$model" --rawfile prompt "$prompt_file" \
        --argjson np "$GALLERY_NUM_PREDICT" --argjson ctx "$GALLERY_NUM_CTX" \
        '{model:$model, prompt:$prompt, stream:false,
          options:{seed:42, num_predict:$np, num_ctx:$ctx}}')
    out=$(curl -s "$OLLAMA_URL/api/generate" -d "$payload")
    if err=$(jq -r '.error // empty' <<<"$out") && [ -n "$err" ]; then
        die "$model: $err"
    fi
    local answer
    answer=$(jq -r '.response' <<<"$out" |
        awk '/<think>/ {skip=1} /<\/think>/ {skip=0; next} !skip' |
        sed -e '/./,$!d')
    if [ -n "$answer" ]; then
        printf '%s\n' "$answer"
    else
        printf '_[the model produced no final answer — it was still reasoning when it hit the token budget]_\n'
    fi
    local thinking_words
    thinking_words=$(jq -r '.thinking // ""' <<<"$out" | wc -w)
    if [ "$thinking_words" -gt 0 ]; then
        printf '\n_[the model produced ~%s words of hidden reasoning before this answer]_\n' "$thinking_words"
    fi
    if [ "$(jq -r '.done_reason' <<<"$out")" = "length" ]; then
        printf '\n_[output truncated at %s tokens]_\n' "$GALLERY_NUM_PREDICT"
    fi
}

mkdir -p "$BENCH_DIR/outputs"
version=$(curl -s "$OLLAMA_URL/api/version" | jq -r .version)

mkdir -p "$BENCH_DIR/outputs/.tmp"
trap 'rm -rf "$BENCH_DIR/outputs/.tmp"' EXIT

for task in $TASKS; do
    file=$(task_file "$task")
    [ -f "$file" ] || die "missing prompt file: $file"
    {
        echo "# Sample outputs — $task"
        echo
        echo "> Auto-generated by [\`scripts/sample-outputs.sh\`](../../scripts/sample-outputs.sh);"
        echo "> unedited model outputs at each model's default sampling settings"
        echo "> (\`seed=42\` for reproducibility), Ollama $version."
        echo "> $(task_blurb "$task")"
        echo
        echo "<details><summary>Full prompt</summary>"
        echo
        echo '```text'
        cat "$file"
        echo '```'
        echo
        echo "</details>"
    } >"$BENCH_DIR/outputs/.tmp/$task.md"
done

# Model-major order so each model is loaded into VRAM only once.
for model in $BENCH_MODELS; do
    for task in $TASKS; do
        log "$model: $task"
        {
            echo
            echo "## \`$model\`"
            echo
            generate "$model" "$(task_file "$task")"
        } >>"$BENCH_DIR/outputs/.tmp/$task.md"
    done
done

for task in $TASKS; do
    mv "$BENCH_DIR/outputs/.tmp/$task.md" "$BENCH_DIR/outputs/$task.md"
    log "wrote $BENCH_DIR/outputs/$task.md"
done
log "gallery done"
